
services:
  db:
    image: mysql:8.0
    container_name: lab07_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: lab07_db
      MYSQL_USER: lab07_user
      MYSQL_PASSWORD: lab07_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  web:
    build: .
    container_name: lab07_flask
    restart: always
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=mysql+pymysql://lab07_user:lab07_pass@db:3306/lab07_db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

volumes:
  mysql_data:
